### ISSUE TITLE
Image links in profile don't work

### ISSUE THREAD

**Issue by ruihildt** [lambda-art-portfolio-bweu/art-portfolio-frontend#16]
I created a Link with router on post pictures in the artist profile page, following the pattern we agreed yesterday night, so `/:userid/posts/:postid`

so when I hover on an image, I get `http://localhost:3000/1/posts/7` for example.
But, when the profile loads, the post itself is `undefined`

This needs fixing could be done with the following the suggestion from @iykekings 

> Basically on the singlepostview you'd connect to the store and find a post with id 7 and artist id 1
> Postid and userid comes the router....so you'd check props.match.params for them
> You only need to connect to the posts reducer

> The better thing to do is to check if the posts exists ...then pull from it but of it doesn't, use fetchPost for single post using it's id to the database with Axios

**Comment by iykekings** [comment]
Okay, great job Rui..I will try to fix this right now

**Comment by iykekings** [comment]
@ruihildt @maximesalomon This issue has been resolved successfully.
